import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar/index";
import { UserProvider } from "@/context/userContext";
import "./globals.css";
import Head from "./head";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Head />
      </head>
      <body>
        <UserProvider>
          <Navbar />
          {children}
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
